<a href="https://colab.research.google.com/github/DennisMuasyaWambua/Next_Word_Predictor/blob/main/NextWordPredictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!python -m spacy download en_core_web_md

In [ ]:
#import spacy

In [ ]:
#embedding_file=spacy.load('en_core_web_md')

In [ ]:
#embedding_file('like').vector

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize,sent_tokenize
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
#from nlp import load_dataset
from nltk.tokenize import word_tokenize,sent_tokenize

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
import nltk
import math
import json
import tensorflow_hub as hub
import spacy

In [ ]:
nltk.download('punkt')
#nltk.download('gutenberg')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
from tensorflow.keras.layers import SimpleRNN,GRU,LSTM,Dense,Embedding,InputLayer,Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import CategoricalCrossentropy
from tensorflow.keras.losses import CategoricalCrossentropy,categorical_crossentropy
from tensorflow.keras import Model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from nltk.corpus import gutenberg

In [ ]:
data = !wget https://elearning.strathmore.edu/pluginfile.php/260789/mod_resource/content/0/corpus.txt --no-check-certificate
data = open("corpus.txt","r")
data=data.read()

In [ ]:
#data=gutenberg.raw(fileids='austen-emma.txt')

In [ ]:
data

'<!DOCTYPE html>\n\n<html  dir="ltr" lang="en" xml:lang="en">\n<head>\n    <title>Strathmore University eLearning System: Log in to the site</title>\n    <link rel="shortcut icon" href="https://elearning.strathmore.edu/theme/image.php/klass/theme/1654770949/favicon" />\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n<meta name="keywords" content="moodle, Strathmore University eLearning System: Log in to the site" />\n<link rel="stylesheet" type="text/css" href="https://elearning.strathmore.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.css" /><script id="firstthemesheet" type="text/css">/** Required in order to fix style inclusion problems in IE with YUI **/</script><link rel="stylesheet" type="text/css" href="https://elearning.strathmore.edu/theme/styles.php/klass/1654770949_1635942521/all" />\n<script>\n//<![CDATA[\nvar M = {}; M.yui = {};\nM.pageloadstarttime = new Date();\nM.cfg = {"wwwroot":"https:\\/\\/elearning.strathmore.edu","sesskey":"Q

In [ ]:
corpus_list=[]
corpus=sent_tokenize(data)
for sent in corpus:
  corpus_list.append([sent])

In [ ]:
corpus

['<!DOCTYPE html>\n\n<html  dir="ltr" lang="en" xml:lang="en">\n<head>\n    <title>Strathmore University eLearning System: Log in to the site</title>\n    <link rel="shortcut icon" href="https://elearning.strathmore.edu/theme/image.php/klass/theme/1654770949/favicon" />\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n<meta name="keywords" content="moodle, Strathmore University eLearning System: Log in to the site" />\n<link rel="stylesheet" type="text/css" href="https://elearning.strathmore.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.css" /><script id="firstthemesheet" type="text/css">/** Required in order to fix style inclusion problems in IE with YUI **/</script><link rel="stylesheet" type="text/css" href="https://elearning.strathmore.edu/theme/styles.php/klass/1654770949_1635942521/all" />\n<script>\n//<!',
 '[CDATA[\nvar M = {}; M.yui = {};\nM.pageloadstarttime = new Date();\nM.cfg = {"wwwroot":"https:\\/\\/elearning.strathmore.edu","sessk

In [ ]:
len(corpus_list)

28

In [ ]:
vectorizer = TfidfVectorizer()

In [ ]:
X = vectorizer.fit_transform(corpus)

In [ ]:
vocab=vectorizer.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
len(vocab)

939

In [ ]:
embeddings_array=X.toarray().T

print(embeddings_array)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.01341036 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [ ]:
pca=PCA(n_components=2)

In [ ]:
dense_embeddings=pca.fit_transform(embeddings_array)

In [ ]:
embeddings_dict={}

In [ ]:
for i in range(len(vocab)):
  embeddings_dict[vocab[i]]=dense_embeddings[i].tolist()

In [ ]:
seq_len=10
tokenizer=Tokenizer()
tokenizer.fit_on_texts([data])
x=tokenizer.texts_to_sequences([data])
#x

In [ ]:
x[0]

[475,
 67,
 67,
 322,
 323,
 199,
 200,
 476,
 199,
 200,
 324,
 139,
 8,
 84,
 14,
 140,
 141,
 42,
 51,
 59,
 142,
 139,
 68,
 239,
 477,
 85,
 17,
 13,
 14,
 8,
 11,
 48,
 325,
 22,
 111,
 48,
 40,
 478,
 201,
 202,
 479,
 69,
 29,
 69,
 65,
 67,
 480,
 481,
 482,
 201,
 45,
 483,
 69,
 1,
 8,
 84,
 14,
 140,
 141,
 42,
 51,
 59,
 142,
 68,
 239,
 326,
 29,
 65,
 163,
 17,
 13,
 14,
 8,
 11,
 48,
 60,
 124,
 22,
 327,
 52,
 240,
 86,
 60,
 328,
 112,
 163,
 18,
 26,
 329,
 29,
 65,
 163,
 330,
 42,
 484,
 51,
 485,
 203,
 486,
 487,
 42,
 488,
 113,
 60,
 18,
 68,
 239,
 326,
 29,
 65,
 163,
 17,
 13,
 14,
 8,
 11,
 48,
 489,
 22,
 111,
 40,
 490,
 143,
 18,
 144,
 78,
 38,
 38,
 60,
 38,
 491,
 492,
 241,
 38,
 493,
 494,
 13,
 14,
 8,
 11,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 40,
 502,
 31,
 48,
 111,
 503,
 6,
 85,
 140,
 504,
 505,
 40,
 242,
 242,
 506,
 32,
 507,
 508,
 331,
 509,
 31,
 510,
 40,
 511,
 40,
 78,
 332,
 61,
 62,
 164,
 145,
 243,
 512,
 513,
 9,
 333,
 62

In [ ]:
len(x[0])

4791

In [ ]:
#tokenizer.get_config()

In [ ]:
vocab_dict=json.loads(tokenizer.get_config().get('word_index'))

In [ ]:
vocab_dict

{"'": 23,
 "''": 336,
 "'anchor'": 781,
 "'core": 77,
 "'css'": 334,
 "'domready'": 983,
 "'en'": 917,
 "'enclose": 977,
 "'http": 641,
 "'https": 154,
 "'jquery": 907,
 "'jquery'": 310,
 "'jqueryprivate'": 455,
 "'login": 768,
 "'lvztr": 706,
 "'process'": 900,
 "'question'": 682,
 "'random62a97af3c44158'": 474,
 "'script'": 378,
 "'text": 637,
 "'theme": 198,
 "'ua": 633,
 '0': 39,
 '00200': 871,
 '01': 878,
 '03': 879,
 '034000': 874,
 '034200': 875,
 '034300': 876,
 '04': 881,
 '1': 31,
 "1'": 635,
 '100': 376,
 '10800': 498,
 '11': 778,
 '11071': 751,
 '12': 295,
 '1200': 500,
 '1583801': 634,
 '163': 739,
 '1635942521': 490,
 '1654770949': 40,
 '17': 240,
 '2': 86,
 '2022': 885,
 '2143': 766,
 '24': 440,
 '248': 762,
 '254': 306,
 '2in3': 340,
 '3': 52,
 '3872': 752,
 '5': 152,
 '59857': 870,
 '6': 777,
 '60458': 905,
 '62a97af3c84c062a97af3c44154': 226,
 '62a97af3c853462a97af3c44155': 229,
 '62a97af3c858e62a97af3c44156': 231,
 '703': 307,
 '72c1ee98367d8bb9c8fa4cd5ee2dc743': 384

In [ ]:
vals=list(vocab_dict.values())
keys=list(vocab_dict.keys())
#keys[vals.index(1)]

In [ ]:
vocab_size=len(keys)

In [ ]:
vocab_size

983

In [ ]:
embedding_array=np.zeros((vocab_size+1,2))
embedding_array.shape

(984, 2)

In [ ]:
for word,i in tokenizer.word_index.items():
  if word in embeddings_dict:
    embedding_vector=embeddings_dict[word]
  #if embedding_vector is not None:
    embedding_array[i]=embedding_vector

In [ ]:
"""for word,i in tokenizer.word_index.items():
  embedding_vector=embedding_file(word).vector
  if embedding_vector is not None:
    embedding_array[i]=embedding_vector"""

'for word,i in tokenizer.word_index.items():\n  embedding_vector=embedding_file(word).vector\n  if embedding_vector is not None:\n    embedding_array[i]=embedding_vector'

In [ ]:
#embedding_array[7306]

In [ ]:
len(x[0])

4791

In [ ]:
x[0][0:15]

[475, 67, 67, 322, 323, 199, 200, 476, 199, 200, 324, 139, 8, 84, 14]

In [ ]:
inner_list=[]
X={}
corpus_length=len(x[0])-seq_len
k=0

for i in range(0,corpus_length,seq_len):
  inner_list.clear()
  for j in range(i,i+seq_len):
    inner_list.append(x[0][j])
  X[k]=inner_list[:]
  k=k+1

In [ ]:
#list(X.values())
x_train=[]
y_train=[]
for it in list(X.values()):
  x_train.append(it[0:-1])
  y_train.append(it[-1])

In [ ]:
x_train[3]

[11, 48, 325, 22, 111, 48, 40, 478, 201]

In [ ]:
len(x_train)

479

In [ ]:
X=np.array(x_train)
#input_seq.shape
y=np.array(y_train).reshape(len(y_train),1)
#target=tf.reshape(tf.constant(y_train),[len(y_train),1])

In [ ]:
y.shape

(479, 1)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [ ]:
X_train.shape

(335, 9)

In [ ]:
y_train

array([[  5],
       [113],
       [398],
       [ 80],
       [ 89],
       [598],
       [ 64],
       [ 52],
       [462],
       [293],
       [360],
       [  2],
       [ 20],
       [  5],
       [183],
       [  1],
       [ 31],
       [  9],
       [  2],
       [391],
       [364],
       [175],
       [ 36],
       [ 31],
       [ 37],
       [405],
       [  1],
       [  4],
       [  2],
       [ 35],
       [ 70],
       [235],
       [ 13],
       [165],
       [528],
       [ 39],
       [ 50],
       [ 90],
       [358],
       [429],
       [ 47],
       [706],
       [ 73],
       [ 78],
       [219],
       [421],
       [431],
       [ 13],
       [ 41],
       [544],
       [ 45],
       [ 74],
       [558],
       [188],
       [ 66],
       [ 87],
       [ 18],
       [ 20],
       [ 20],
       [  1],
       [  4],
       [ 48],
       [ 18],
       [187],
       [ 25],
       [875],
       [ 14],
       [149],
       [ 10],
       [459],
       [ 63],
      

In [ ]:
input_seq,test_seq,y_true,y_hat=tf.constant(X_train),tf.constant(X_test),tf.constant(y_train),tf.constant(y_test)

In [ ]:
input_seq

<tf.Tensor: shape=(335, 9), dtype=int64, numpy=
array([[  5,  24,  24, ..., 237, 279, 183],
       [309,  22,  40, ..., 220, 110, 166],
       [396,  31,  91, ...,  82, 157,  30],
       ...,
       [153,   1, 187, ...,  92,  32, 435],
       [  1,  27,  46, ...,  10,  12,  12],
       [  2, 147,  47, ...,  58,   2,  85]])>

In [ ]:
tf.reduce_max(input_seq)+1

<tf.Tensor: shape=(), dtype=int64, numpy=984>

In [ ]:
input=Input(shape=(seq_len-1,))
x=Embedding(input_dim=vocab_size+1,input_length=seq_len-1,output_dim=2,weights=[embedding_array],trainable=True)(input)
x=SimpleRNN(128)(x)
x=Dense(64)(x)
x=Dense(32)(x)
output=Dense(vocab_size,activation="softmax")(x)
model=Model(input,output)

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 9)]               0         
                                                                 
 embedding_1 (Embedding)     (None, 9, 2)              1968      
                                                                 
 simple_rnn (SimpleRNN)      (None, 128)               16768     
                                                                 
 dense (Dense)               (None, 64)                8256      
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 983)               32439     
                                                                 
Total params: 61,511
Trainable params: 61,511
Non-trainable p

In [ ]:
model.compile(optimizer=Adam(0.001),loss=tf.keras.losses.sparse_categorical_crossentropy,metrics=['accuracy'])

In [ ]:
model.fit(input_seq,y_true,epochs=100)

Epoch 1/100
11/11 [==============================] - 1s 11ms/step - loss: 0.3387 - accuracy: 0.9015
Epoch 2/100
11/11 [==============================] - 0s 12ms/step - loss: 0.1614 - accuracy: 0.9522
Epoch 3/100
11/11 [==============================] - 0s 12ms/step - loss: 0.0693 - accuracy: 0.9761
Epoch 4/100
11/11 [==============================] - 0s 11ms/step - loss: 0.0346 - accuracy: 0.9910
Epoch 5/100
11/11 [==============================] - 0s 11ms/step - loss: 0.0255 - accuracy: 0.9940
Epoch 6/100
11/11 [==============================] - 0s 11ms/step - loss: 0.0196 - accuracy: 0.9970
Epoch 7/100
11/11 [==============================] - 0s 10ms/step - loss: 0.0181 - accuracy: 0.9940
Epoch 8/100
11/11 [==============================] - 0s 11ms/step - loss: 0.0166 - accuracy: 0.9940
Epoch 9/100
11/11 [==============================] - 0s 11ms/step - loss: 0.0139 - accuracy: 0.9940
Epoch 10/100
11/11 [==============================] - 0s 10ms/step - loss: 0.0126 - accuracy: 0.9940

In [ ]:
model.evaluate(test_seq,y_hat)

5/5 [==============================] - 0s 4ms/step - loss: 33.6357 - accuracy: 0.0764


[33.63566970825195, 0.0763888880610466]

In [ ]:
input_text=["she was such a good person"]
#input_text=["he was such a good person and honestly speaking he did make good use of his"]
#input_text=["can you please"]
#input_text=["marriage is such a beautiful"]
toks=tokenizer.texts_to_sequences(input_text)
ins=pad_sequences(toks,maxlen=seq_len-1)
input_tensor=tf.constant(ins)
input_tensor

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[  0,   0,   0,   0,   0,   0,   0, 911,   5]], dtype=int32)>

In [ ]:
pred=model.predict(input_tensor)
keys[vals.index(np.argmax(pred))]

'class'

In [ ]:
input_text[0]=input_text[0]+' '+keys[vals.index(np.argmax(pred))]
input_text[0]

'she was such a good person class'

In [ ]:
for i in range(10):
  toks=tokenizer.texts_to_sequences(input_text)
  ins=pad_sequences(toks,maxlen=seq_len-1)
  input_tensor=tf.constant(ins)
  pred=model.predict(input_tensor)
  input_text[0]=input_text[0]+' '+keys[vals.index(np.argmax(pred))]

print(input_text)

['she was such a good person p library path moodle editor notifications dialogue moodle atto susams delegate']


In [ ]:
sort_pred=np.argsort(pred[0])
pred_words=np.flip(sort_pred[-5:])
for index in pred_words:
  print(keys[vals.index(index)])

delegate
lib
util
autolinker
mission
